-- Add missing columns to fixtures_all_new table
-- These columns exist in the database but weren't in the original migration

-- Add team logo columns
ALTER TABLE PUBLIC.FIXTURES_ALL_NEW
    ADD COLUMN IF NOT EXISTS TEAM1_LOGO TEXT, ADD COLUMN IF NOT EXISTS TEAM2_LOGO TEXT;

-- Add match group and URL slug columns
ALTER TABLE PUBLIC.FIXTURES_ALL_NEW
    ADD COLUMN IF NOT EXISTS MATCH_GROUP TEXT, ADD COLUMN IF NOT EXISTS LFF_URL_SLUG TEXT DEFAULT '';

-- Add statistics columns
ALTER TABLE PUBLIC.FIXTURES_ALL_NEW
    ADD COLUMN IF NOT EXISTS HOME_SHOTS_TOTAL INTEGER, ADD COLUMN IF NOT EXISTS AWAY_SHOTS_TOTAL INTEGER, ADD COLUMN IF NOT EXISTS HOME_SHOTS_ON_TARGET INTEGER, ADD COLUMN IF NOT EXISTS AWAY_SHOTS_ON_TARGET INTEGER, ADD COLUMN IF NOT EXISTS HOME_SHOTS_OFF_TARGET INTEGER, ADD COLUMN IF NOT EXISTS AWAY_SHOTS_OFF_TARGET INTEGER;

-- Add attack statistics columns
ALTER TABLE PUBLIC.FIXTURES_ALL_NEW
    ADD COLUMN IF NOT EXISTS HOME_ATTACKS INTEGER, ADD COLUMN IF NOT EXISTS AWAY_ATTACKS INTEGER, ADD COLUMN IF NOT EXISTS HOME_DANGEROUS_ATTACKS INTEGER, ADD COLUMN IF NOT EXISTS AWAY_DANGEROUS_ATTACKS INTEGER;

-- Add corner statistics columns
ALTER TABLE PUBLIC.FIXTURES_ALL_NEW
    ADD COLUMN IF NOT EXISTS HOME_CORNERS INTEGER, ADD COLUMN IF NOT EXISTS AWAY_CORNERS INTEGER;

-- Add statistics and events columns if they don't exist
ALTER TABLE PUBLIC.FIXTURES_ALL_NEW
    ADD COLUMN IF NOT EXISTS STATISTICS JSONB, ADD COLUMN IF NOT EXISTS EVENTS JSONB;