-- Add columns to track player stats updates after matches
ALTER TABLE MATCHES
    ADD COLUMN IF NOT EXISTS PLAYER_STATS_UPDATED BOOLEAN DEFAULT FALSE, ADD COLUMN IF NOT EXISTS PLAYER_STATS_UPDATED_AT TIMESTAMP WITH TIME ZONE;

-- Add index for efficient querying of matches that need player stats updates
CREATE INDEX IF NOT EXISTS IDX_MATCHES_PLAYER_STATS_UPDATED
ON MATCHES(PLAYER_STATS_UPDATED, STATUS, DATE DESC);

-- Add surname column to banga_playerss table if it doesn't exist
ALTER TABLE BANGA_PLAYERSS
    ADD COLUMN IF NOT EXISTS SURNAME TEXT;

-- Add updated_at column to banga_playerss table if it doesn't exist
ALTER TABLE BANGA_PLAYERSS
    ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(
    );

-- Create index for efficient player lookups
CREATE INDEX IF NOT EXISTS IDX_BANGA_PLAYERSS_NAME_TEAM
ON BANGA_PLAYERSS(NAME, TEAM_KEY);

-- Add trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION UPDATE_UPDATED_AT_COLUMN(
) RETURNS TRIGGER AS
    $$     BEGIN NEW.UPDATED_AT = NOW();
    RETURN NEW;
END;
$$     LANGUAGE 'plpgsql';
 
-- Create trigger for banga_playerss table
DROP   TRIGGER IF EXISTS UPDATE_BANGA_PLAYERSS_UPDATED_AT ON BANGA_PLAYERSS;
CREATE TRIGGER UPDATE_BANGA_PLAYERSS_UPDATED_AT BEFORE
UPDATE ON BANGA_PLAYERSS FOR EACH ROW EXECUTE FUNCTION UPDATE_UPDATED_AT_COLUMN(
);